//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESY_PRACOWNIKA
    {
        public int IDP { get; set; }
        public int IDA { get; set; }
        public string ULICA { get; set; }
        public string NR_BUDYNKU { get; set; }
        public string NR_LOKALU { get; set; }
        public string MIASTO { get; set; }
    }
}
