//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CZAS_PRACY_MASZYN
    {
        public int ID_ZLECENIA { get; set; }
        public int ID_MASZYNY { get; set; }
        public string NR_EWIDENCYJNY { get; set; }
        public Nullable<int> ILOSC_DNI_PRACY { get; set; }
    }
}
