//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_STATUSU_ZLECENIA
    {
        public int ID_ZLECENIA { get; set; }
        public int ID_STATUSU_ZLECENIA { get; set; }
        public Nullable<System.DateTime> DATA_ZMIANY { get; set; }
    
        public virtual STATUS_ZLECENIA STATUS_ZLECENIA { get; set; }
        public virtual ZLECENIA ZLECENIA { get; set; }
    }
}
