
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class DOSTAWA
{

    public int ID_DOSTAWY { get; set; }

    public Nullable<int> ID_ADRESU { get; set; }

    public Nullable<int> ID_FIRMY { get; set; }

    public Nullable<int> DLUGOSC_TRASY { get; set; }



    public virtual ADRESY ADRESY { get; set; }

    public virtual FIRMY FIRMY { get; set; }

}

}
