//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KREATOR_FAKTUR
    {
        public int ID_FAKTURY { get; set; }
        public string NAZWA_FIRMY { get; set; }
        public string ADRES_EMAIL { get; set; }
        public string NR_TELEFONU { get; set; }
        public string NIP { get; set; }
        public Nullable<int> ID_ZLECENIA { get; set; }
        public Nullable<System.DateTime> DATA_WYSTAWIENIA { get; set; }
        public Nullable<System.DateTime> DATA_PLATNOSCI { get; set; }
        public Nullable<decimal> KWOTA { get; set; }
        public string WALUTA { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
    }
}
