
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class LOKALIZACJA
{

    public int ID_LOKALIZACJI { get; set; }

    public string SEKTOR { get; set; }

    public string ALEJKA { get; set; }

    public string REAGAL { get; set; }

    public string POZIOM { get; set; }

    public string KOSZ { get; set; }

}

}
