
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class MASA_PRODUKTU
{

    public string NAZWA_PRODUKTU { get; set; }

    public Nullable<int> MASA_PRODUKTU1 { get; set; }

}

}
