//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASZYNY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASZYNY()
        {
            this.ZESPOL_MASZYN = new HashSet<ZESPOL_MASZYN>();
            this.PROCES = new HashSet<PROCES>();
        }
    
        public int ID_MASZYNY { get; set; }
        public Nullable<int> ID_MODEL_MASZYNY { get; set; }
        public string NR_EWIDENCYJNY { get; set; }
    
        public virtual MODELE_MASZYN MODELE_MASZYN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZESPOL_MASZYN> ZESPOL_MASZYN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCES> PROCES { get; set; }
    }
}
