
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class MODELE_MASZYN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MODELE_MASZYN()
    {

        this.MASZYNY = new HashSet<MASZYNY>();

        this.PARAMETRY_MASZYNY = new HashSet<PARAMETRY_MASZYNY>();

    }


    public int ID_MODEL_MASZYNY { get; set; }

    public string MODEL { get; set; }

    public string MARKA { get; set; }

    public string TYP_MASZYNY { get; set; }

    public int PRĘDKOŚĆ { get; set; }

    public int POSUW { get; set; }

    public decimal KOSZT_ZA_H { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MASZYNY> MASZYNY { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PARAMETRY_MASZYNY> PARAMETRY_MASZYNY { get; set; }

}

}
