//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBCIAZENIE_MASZYN
    {
        public System.DateTime DATA_DZIEN { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string TYP_MASZYNY { get; set; }
        public string NR_EWIDENCYJNY { get; set; }
    }
}
