
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class PARAMETRY
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PARAMETRY()
    {

        this.PARAMETRY_MASZYNY = new HashSet<PARAMETRY_MASZYNY>();

        this.PARAMETRY_MATERIALU = new HashSet<PARAMETRY_MATERIALU>();

    }


    public int ID_PARAMETR { get; set; }

    public string NAZWA { get; set; }

    public string JEDNOSTKA_MIARY { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PARAMETRY_MASZYNY> PARAMETRY_MASZYNY { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PARAMETRY_MATERIALU> PARAMETRY_MATERIALU { get; set; }

}

}
