
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class PENSJE
{

    public int ID_PRACOWNIK { get; set; }

    public string NAZWISKO { get; set; }

    public string IMIE { get; set; }

    public decimal WARTOSC { get; set; }

    public int ID_OKRES { get; set; }

    public string NAZWA { get; set; }

    public Nullable<double> PENSJA_MSC { get; set; }

    public System.DateTime DATA_START { get; set; }

    public Nullable<System.DateTime> DATA_KONIEC { get; set; }

}

}
