//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class POJAZDY
    {
        public int ID_POJAZDU { get; set; }
        public Nullable<int> ID_FIRMY { get; set; }
        public string MARKA { get; set; }
        public string MODEL { get; set; }
        public string NUMER_REJESTRACYJNY { get; set; }
        public Nullable<decimal> STAWKA { get; set; }
        public string NOSNOSC { get; set; }
        public string GABARYTY { get; set; }
    
        public virtual FIRMY FIRMY { get; set; }
    }
}
