//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNIK_DANE
    {
        public int ID_PRACOWNIK { get; set; }
        public string NAZWISKO { get; set; }
        public string IMIE { get; set; }
        public string TELEFON { get; set; }
        public string PESEL { get; set; }
        public System.DateTime DATA_START { get; set; }
        public Nullable<System.DateTime> DATA_KONIEC { get; set; }
        public string STANOWISKO { get; set; }
        public string ULICA { get; set; }
        public string NR_BUDYNKU { get; set; }
        public string NR_LOKALU { get; set; }
        public string KOD_POCZTOWY { get; set; }
        public string MIASTO { get; set; }
        public string KRAJ { get; set; }
    }
}
