
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class PRODUKCJA_POLPRODUKTU
{

    public Nullable<int> ID_POLPRODUKTU { get; set; }

    public Nullable<int> ID_PRODUKTU { get; set; }

    public System.DateTime CZAS_REALIZACJI_MONTAZU { get; set; }

    public decimal KOSZT_REALIZACJI_MONTAZU { get; set; }



    public virtual POLPRODUKTY POLPRODUKTY { get; set; }

    public virtual PRODUKT PRODUKT { get; set; }

}

}
