//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUKT()
        {
            this.PRODUKCJA_POLPRODUKTU = new HashSet<PRODUKCJA_POLPRODUKTU>();
            this.ZMIANA_STANU_MAGAZYNU_PRODUKTOW = new HashSet<ZMIANA_STANU_MAGAZYNU_PRODUKTOW>();
            this.ZLECENIE_PRODUKT = new HashSet<ZLECENIE_PRODUKT>();
        }
    
        public int ID_PRODUKTU { get; set; }
        public string NAZWA_PRODUKTU { get; set; }
        public string OPIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKCJA_POLPRODUKTU> PRODUKCJA_POLPRODUKTU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZMIANA_STANU_MAGAZYNU_PRODUKTOW> ZMIANA_STANU_MAGAZYNU_PRODUKTOW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZLECENIE_PRODUKT> ZLECENIE_PRODUKT { get; set; }
    }
}
