//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKTY_POZOSTALE_DO_TRANSPORTU
    {
        public int ID_ZLECENIA { get; set; }
        public int ID_PRODUKTU { get; set; }
        public string NAZWA_PRODUKTU { get; set; }
        public Nullable<int> PRODUKTY_GOTOWE_DO_TRANSPORTU { get; set; }
    }
}
