//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPIS_UZYTKOWNIKOW
    {
        public int ID_UZYTKOWNIKA { get; set; }
        public Nullable<int> ID_PRACOWNIK { get; set; }
        public int UPRAWNIENIA { get; set; }
        public string NAZWA_LOGOWANIE { get; set; }
        public string HASLO { get; set; }
        public string POZIOM_UPRAWNIEN { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public string PESEL { get; set; }
    }
}
