//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAN_MATERIALY_NAZWY
    {
        public Nullable<int> ID_MATERIALU { get; set; }
        public Nullable<int> ID_ZLECENIA { get; set; }
        public Nullable<int> ID_LOKALIZACJI { get; set; }
        public Nullable<int> STAN { get; set; }
        public string SEKTOR { get; set; }
        public string ALEJKA { get; set; }
        public string NAZWA { get; set; }
    }
}
