//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAWKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAWKA()
        {
            this.STAWKA_PRACOWNICY = new HashSet<STAWKA_PRACOWNICY>();
        }
    
        public int ID_STAWKA { get; set; }
        public decimal WARTOSC { get; set; }
        public int ID_OKRES { get; set; }
    
        public virtual OKRES OKRES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAWKA_PRACOWNICY> STAWKA_PRACOWNICY { get; set; }
    }
}
