
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class WALUTY
{

    public int ID_WALUTY { get; set; }

    public string NAZWA { get; set; }

    public float KURS_DO_PLN { get; set; }

    public System.DateTime DATA_KURS { get; set; }

}

}
