//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAMOWIENIA
    {
        public int ID_ZAMOWIENIA { get; set; }
        public Nullable<System.DateTime> DATA_ZAMOWIENIA { get; set; }
        public Nullable<System.DateTime> DATA_REALIZACJI { get; set; }
        public Nullable<int> ID_FIRMY { get; set; }
        public Nullable<int> ID_STATUSU_ZAMOWIENIA { get; set; }
    
        public virtual FIRMY FIRMY { get; set; }
        public virtual STATUS_ZAMOWIENIA STATUS_ZAMOWIENIA { get; set; }
    }
}
