
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class ZAPOTRZEBOWANIE_MATERIAL
{

    public Nullable<int> ID_ZLECENIA { get; set; }

    public string NAZWA_PRODUKTU { get; set; }

    public string NAZWA { get; set; }

    public string OZNACZENIE_SUROWCA { get; set; }

    public string Nazwa_MATERIAL { get; set; }

    public Nullable<int> WARTOŚĆ { get; set; }

    public Nullable<int> LICZBA_SZTUK { get; set; }

}

}
