//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZESPOL_MASZYN
    {
        public int ID_ZESPOL_MASZYN { get; set; }
        public int ID_REALIZACJA_PRODUKCJA { get; set; }
        public int ID_MASZYNY { get; set; }
    
        public virtual MASZYNY MASZYNY { get; set; }
        public virtual REALIZACJA_PRODUKCJA REALIZACJA_PRODUKCJA { get; set; }
    }
}
