//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class zestawienie
    {
        public int ID_ZLECENIA { get; set; }
        public Nullable<decimal> wydatki { get; set; }
        public Nullable<decimal> obroty { get; set; }
        public Nullable<decimal> zarobek { get; set; }
    }
}
