//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class zestawienie
    {
        public int ID_ZLECENIA { get; set; }
        public System.DateTime DATA_ZLECENIA { get; set; }
        public System.DateTime DATA_REALIZACJI { get; set; }
        public Nullable<decimal> Kwota_pobrana_za_zlecenie { get; set; }
        public Nullable<decimal> Kosz_wykonania_zlecenia { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
