
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJEKTapp
{

using System;
    using System.Collections.Generic;
    
public partial class ZLECENIA_LOKALIZACJA
{

    public int ID_ZLECENIA { get; set; }

    public Nullable<int> ID_PRODUKTU { get; set; }

    public string NAZWA_PRODUKTU { get; set; }

    public Nullable<int> ILOSC { get; set; }

    public string SEKTOR { get; set; }

    public string ALEJKA { get; set; }

}

}
