//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJEKTapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZLECENIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZLECENIA()
        {
            this.FAKTURY = new HashSet<FAKTURY>();
            this.REALIZACJA_PRODUKCJA = new HashSet<REALIZACJA_PRODUKCJA>();
        }
    
        public int ID_ZLECENIA { get; set; }
        public System.DateTime DATA_ZLECENIA { get; set; }
        public System.DateTime DATA_REALIZACJI { get; set; }
        public Nullable<int> ID_FIRMY { get; set; }
        public Nullable<int> ID_STATUS_ZLECENIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAKTURY> FAKTURY { get; set; }
        public virtual FIRMY FIRMY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REALIZACJA_PRODUKCJA> REALIZACJA_PRODUKCJA { get; set; }
        public virtual STATUS_ZLECENIA STATUS_ZLECENIA { get; set; }
    }
}
